# Generated by Django 3.2.22 on 2023-10-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name="o'zgargan vaqt")),
                ('is_published', models.BooleanField(default=True, verbose_name='tahrir')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
